name: Decir Hola Mundo

env:
  U_VERSION: ubuntu-latest
#Con esto configuramos el trigger
on:
  push: 
    branches: [main]

#Con esto configuramos las acciones
jobs:
  saludar:
    #runs on configura el so sobre el que corre
    runs-on: $U_VERSION
    #steps dice que acciones va a hacer
    steps:
      - name: Decir Hola
        run: echo "Hola mundo de HAB"
      - name: Pausa
        run: sleep 1

  darHora:
    runs-on: $U_VERSION
    needs: saludar
    steps:
      - name: Que hora es
        run: echo "la hora del servidor es $(date)"
    
  despedir:
    runs-on: $U_VERSION
    needs: darHora #Con needs podemos crear dependencias para que no se ejecute un job hasta que no se cumplan
    steps:    
      - name: Decir Chao
        run: echo "Chao mundo de HAB"

  acciones:
    runs-on: $U_VERSION
    steps:
      - name: mostrar secreto
        run: echo ${{secrets.MI_SECRET}}
      
      - name: mostrar variable
        run: echo ${{ vars.MI_VARIABLE}}
  
  errores:
    runs-on: windows-latest
    steps:
      - name: provocar error
        run:  ls -la $GITHUB_WORKSPACE

      - name: manejar error
        if: ${{ failure() }}
        run: echo "Error"
        continue-on-error: true
        
        # Con exit 1 el error detiene la action
