name: Decir Hola Mundo

on: [push]

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Decir Hola
        run: echo "Hola mundo de HAB"
      - name: Decir Chao
        run: echo "Chao mundo de HAB"
      - run: echo "mensaje sin nombre"