name: Decir Hola Mundo

#Con esto configuramos el trigger
on:
  push: 
    branches: [main]

#Con esto configuramos las acciones
jobs:
  saludar:
    #runs on configura el so sobre el que corre
    runs-on: ubuntu-latest
    #steps dice que acciones va a hacer
    steps:
      - name: Decir Hola
        run: echo "Hola mundo de HAB"
      - name: Pausa
        run: sleep 1 
      - name: Que hora es
        run: echo "la hora del servidor es $(date)"
      
  despedir:
    runs-on: ubuntu-latest
    steps:    
      - name: Decir Chao
        run: echo "Chao mundo de HAB"

  acciones:
    runs-on: ubuntu-latest
    steps:
      - name: mostrar secreto
        run: echo ${{secrets.MI_SECRET}}
      
      - name: mostrar variable
        run: echo ${{ vars.MI_VARIABLE}}
  
  errores:
    runs-on: windows-latest
    steps:
      - name: provocar error
        run:  ls -la $GITHUB_WORKSPACE
        continue-on-error: true
        # Con exit 1 el error detiene la action
